test_that("cor_convert works for scalars, vectors, and matrices", {
  S <- "spearman"
  K <- "kendall"
  P <- "pearson"

  rs <- cor_randPD(4)
  rk <- cor_randPD(4)
  rp <- cor_randPD(4)

  rsk <- cor_convert(rs, S, K)
  rsp <- cor_convert(rs, S, P)
  rks <- cor_convert(rk, K, S)
  rkk <- cor_convert(rk, K, K)
  rkp <- cor_convert(rk, K, P)
  rps <- cor_convert(rp, P, S)
  rpk <- cor_convert(rp, P, K)
  rpp <- cor_convert(rp, P, P)
  rss <- cor_convert(rs, S, S)

  expect_identical(rs, rss)
  expect_identical(rk, rkk)
  expect_identical(rp, rpp)

  expect_equal(cor_convert( 0.0, S, K),  0.0)
  expect_equal(cor_convert( 0.0, S, P),  0.0)
  expect_equal(cor_convert( 0.0, K, S),  0.0)
  expect_equal(cor_convert( 0.0, K, K),  0.0)
  expect_equal(cor_convert( 0.0, K, P),  0.0)
  expect_equal(cor_convert( 0.0, P, S),  0.0)
  expect_equal(cor_convert( 0.0, P, K),  0.0)
  expect_equal(cor_convert( 0.0, P, P),  0.0)
  expect_equal(cor_convert( 0.0, S, S),  0.0)
  expect_equal(cor_convert( 1.0, S, K),  1.0)
  expect_equal(cor_convert( 1.0, S, P),  1.0)
  expect_equal(cor_convert( 1.0, K, S),  1.0)
  expect_equal(cor_convert( 1.0, K, K),  1.0)
  expect_equal(cor_convert( 1.0, K, P),  1.0)
  expect_equal(cor_convert( 1.0, P, S),  1.0)
  expect_equal(cor_convert( 1.0, P, K),  1.0)
  expect_equal(cor_convert( 1.0, P, P),  1.0)
  expect_equal(cor_convert( 1.0, S, S),  1.0)
  expect_equal(cor_convert(-1.0, S, K), -1.0)
  expect_equal(cor_convert(-1.0, S, P), -1.0)
  expect_equal(cor_convert(-1.0, K, S), -1.0)
  expect_equal(cor_convert(-1.0, K, K), -1.0)
  expect_equal(cor_convert(-1.0, K, P), -1.0)
  expect_equal(cor_convert(-1.0, P, S), -1.0)
  expect_equal(cor_convert(-1.0, P, K), -1.0)
  expect_equal(cor_convert(-1.0, P, P), -1.0)
  expect_equal(cor_convert(-1.0, S, S), -1.0)
})
