---
title: "Profile Rank"
author: "Alex Knudson"
date: "5/29/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      comment = NA,
                      cache = TRUE,
                      warning = FALSE,
                      message = FALSE)

library(ggplot2)

library(microbenchmark)
library(fastrank)
library(data.table)

library(reticulate)
use_python("/home/alex/miniconda3/envs/bigsimr/bin/python")
```


# The functions

```{r, echo=TRUE}
rank_dc  <- fastrank::fastrank_num_avg
rank_dt  <- function(x) data.table::frankv(x, ties.method = "average")
rank_new <- function(x) .Internal(rank(x, length(x), "average"))

scipy <- import("scipy")
rank_py  <- function(x) scipy$stats$rankdata(x, method='average')
```

# The Benchmarks

**Small Vector**

```{r}
n  <- 1e2
xx <- as.numeric(sample(n, n, replace=TRUE))
yy <- rnorm(n)

mbx <- microbenchmark(rank(xx),
                      rank_new(xx),
                      rank_dc(xx),
                      rank_dt(xx),
                      rank_py(xx),
                      times = 10000)

mby <- microbenchmark(rank(yy),
                      rank_new(yy),
                      rank_dc(yy),
                      rank_dt(yy),
                      rank_py(yy),
                      times = 10000)
```


```{r}
autoplot(mbx) + 
  labs(title = "Integer Samples", subtitle = paste("N =", n))

autoplot(mby) + 
  labs(title = "Normal Samples", subtitle = paste("N =", n))
```




**Medium Vector**

```{r}
n  <- 1e3
xx <- as.numeric(sample(n, n, replace=TRUE))
yy <- rnorm(n)

mbx <- microbenchmark(rank(xx),
                      rank_new(xx),
                      rank_dc(xx),
                      rank_dt(xx),
                      rank_py(xx),
                      times = 10000)

mby <- microbenchmark(rank(yy),
                      rank_new(yy),
                      rank_dc(yy),
                      rank_dt(yy),
                      rank_py(yy),
                      times = 10000)
```


```{r}
autoplot(mbx) + 
  labs(title = "Integer Samples", subtitle = paste("N =", n))

autoplot(mby) + 
  labs(title = "Normal Samples", subtitle = paste("N =", n))
```

**Big Vector**

```{r}
n  <- 1e4
xx <- as.numeric(sample(n, n, replace=TRUE))
yy <- rnorm(n)

mbx <- microbenchmark(rank(xx),
                      rank_new(xx),
                      rank_dc(xx),
                      rank_dt(xx),
                      rank_py(xx),
                      times = 10000)

mby <- microbenchmark(rank(yy),
                      rank_new(yy),
                      rank_dc(yy),
                      rank_dt(yy),
                      rank_py(yy),
                      times = 10000)
```


```{r}
autoplot(mbx) + 
  labs(title = "Integer Samples", subtitle = paste("N =", n))

autoplot(mby) + 
  labs(title = "Normal Samples", subtitle = paste("N =", n))
```


**Huge Vector**

```{r}
n  <- 1e5
xx <- as.numeric(sample(n, n, replace=TRUE))
yy <- rnorm(n)

mbx <- microbenchmark(rank(xx),
                      rank_new(xx),
                      rank_dc(xx),
                      rank_dt(xx),
                      rank_py(xx),
                      times = 100)

mby <- microbenchmark(rank(yy),
                      rank_new(yy),
                      rank_dc(yy),
                      rank_dt(yy),
                      rank_py(yy),
                      times = 100)
```


```{r}
autoplot(mbx) + 
  labs(title = "Integer Samples", subtitle = paste("N =", n))

autoplot(mby) + 
  labs(title = "Normal Samples", subtitle = paste("N =", n))
```

**Ludicrous Vector**

```{r}
n  <- 1e6
xx <- as.numeric(sample(n, n, replace=TRUE))
yy <- rnorm(n)

mbx <- microbenchmark(rank(xx),
                      rank_new(xx),
                      rank_dc(xx),
                      rank_dt(xx),
                      rank_py(xx),
                      times = 10)

mby <- microbenchmark(rank(yy),
                      rank_new(yy),
                      rank_dc(yy),
                      rank_dt(yy),
                      rank_py(yy),
                      times = 10)
```


```{r}
autoplot(mbx) + 
  labs(title = "Integer Samples", subtitle = paste("N =", n))

autoplot(mby) + 
  labs(title = "Normal Samples", subtitle = paste("N =", n))
```
