---
title: "TCGA BRCA Simulations"
author: "Alex Knudson"
date: "6/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

reticulate::use_condaenv("bigsimr-gpu")

library(tidyverse)
devtools::load_all()

mom_gamma <- function(x) {
  m <- mean(x)
  s <- sd(x)
  list("gamma", shape = m^2 / s^2, rate = m / s^2)
}

mom_nbinom <- function(x) {
  m <- mean(x)
  s <- sd(x)
  list("nbinom", size = m^2 / (s^2 - m), prob = m / s^2)
}
```


```{r}
reticulate::py_config()
```

# Get TCGA BRCA Data

```{r}
# Load in the data
dat0 <- readRDS(
  file = "~/Downloads/complete_processed_tcga2stat_RNASeq2_with_clinical.rds")

# Select just the BRCA genes
brca0 <- dat0 %>%
  filter(disease == "BRCA") %>%
  select(-c("patient":"tumorsize"))

brca1 <- round(brca0, 0)

# Filter down the brca data set
brca_median <- apply(brca1, 2, median)
top_percentile <- 0.75
cut_point <- quantile(brca_median, top_percentile)
keep_genes <- names(brca_median)[brca_median >= cut_point]

(d <- length(keep_genes))

brca2 <- brca1 %>%
  select(all_of(keep_genes))


# brca_rho <- bigsimr::fastCor(brca2, method = "kendall")

brca_margins <- apply(brca2, 2, mom_nbinom)
```




# Simulations and Timing

## Setup

```{r}
cores <- c(20, 10, 1)
type <- c("pearson", "spearman", "kendall")
# cores <- c(20)
n <- nrow(brca0)
adjustForDiscrete <- c(FALSE)
top_percentile <- c(0.99, 0.975, 0.95, 0.90, 0.85, 0.80, 0.75)
# top_percentile <- c(0.99, 0.975)

sim_pars <- expand.grid(n = n,
                        adj = adjustForDiscrete,
                        q = top_percentile,
                        cores = cores, 
                        type = type,
                        stringsAsFactors = FALSE)

sim_pars
```



```{r}
unlink("sims_brca", recursive = TRUE)
dir.create("sims_brca", showWarnings = FALSE)

brca_median <- apply(brca1, 2, median)

res <- data.frame()
for (i in 1:nrow(sim_pars)) {
  type  <- sim_pars$type[i]
  cores <- sim_pars$cores[i]
  n     <- sim_pars$n[i]
  adj   <- sim_pars$adj[i]
  q     <- sim_pars$q[i]
  
  # Subset the BRCA data to the cutpoint
  cut_point <- quantile(brca_median, q)
  keep_genes <- names(brca_median)[brca_median >= cut_point]
  (d <- length(keep_genes))
  
  brca_tmp <- brca1 %>%
    select(all_of(keep_genes))
  
  brca_rho     <- fastCor(brca_tmp, method = type)
  brca_margins <- apply(brca_tmp, 2, mom_nbinom)
  
  # Simulate new data
  time_data <- system.time({
    x <- rvec(
      n = n,
      rho = brca_rho,
      params = brca_margins,
      cores = cores,
      type = type,
      adjustForDiscrete = adj
    )
  })
  
  Rho_hat     <- fastCor(x, method = type)
  margins_hat <- apply(x, 2, mom_nbinom)
  
  # Save the sims in case
  id <- paste0(
    "d", d,
    "-N", n,
    "-c", cores,
    "-Cor", type,
    "-adj", as.character(adj),
    "-dev", "GPU",
    "-lib", "bigsimr"
  )
  saveRDS(x, file = paste0("sims_brca/", id, ".rds"))
  
  # Save the results
    res <- rbind(res, data.frame(
      method = "bigsimr",
      device = "GPU",
      type = type,
      cores = cores,
      margins = "nbinom",
      adjustForDiscrete = adj,
      d = d,
      N = n,
      sim_time = unname(time_data["elapsed"])
    ))
}
```

