---
title: "Format of Marginals"
author: "Alex Knudson"
date: "10/8/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(devtools)
load_all()
```


```{r, eval=FALSE}
all_dists <- list(
  list(dist = "beta", shape1, shape2),
  list(dist = "binom", size, prob),
  list(dist = "cauchy", location, scale),
  list(dist = "chisq", df),
  list(dist = "exp", rate),
  list(dist = "f", df1, df2),
  list(dist = "gamma", shape, rate),
  list(dist = "geom", prob),
  list(dist = "hyper", m, n, k),
  list(dist = "logis", location, scale),
  list(dist = "lnorm", meanlog, sdlog),
  list(dist = "nbinom", size, prob),
  list(dist = "norm", mean, sd),
  list(dist = "pois", lambda),
  list(dist = "t", df),
  list(dist = "unif", min, max),
  list(dist = "weibull", shape, scale),
  list(dist = "wilcox", m, n),
  list(dist = "signrank", n)
)
```



```{r}
d <- 5
rho <- rcor(d)
margins <- list(
  list("nbinom", size = 5, prob = 0.3),
  list("exp", rate = 4),
  list("binom", size = 5, prob = 0.7),
  list("norm", mean = 10, sd = 3),
  list("pois", lambda = 10)
)

margins2 <- list(
  list("nbinom", 5, 0.3),
  list("exp", 4),
  list("binom", 5, 0.7),
  list("norm", 10, 3),
  list("pois", 10)
)

rvec(10, rho, margins, cores = 6, type = "pearson")
rvec(10, rho, margins2, cores = 6, type = "pearson")
```

