# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.cor_convert_double <- function(X, CASE) {
    .Call(`_bigsimr_cor_convert_double`, X, CASE)
}

.cor_convert_matrix <- function(X, CASE) {
    .Call(`_bigsimr_cor_convert_matrix`, X, CASE)
}

.cor_randPSD <- function(d, k) {
    .Call(`_bigsimr_cor_randPSD`, d, k)
}

hermite <- function(x, n) {
    .Call(`_bigsimr_hermite`, x, n)
}

Hn <- function(x, n) {
    .Call(`_bigsimr_Hn`, x, n)
}

Hp <- function(x, n) {
    .Call(`_bigsimr_Hp`, x, n)
}

Gn0d <- function(A, B, a, b, sAsB_inv, k) {
    .Call(`_bigsimr_Gn0d`, A, B, a, b, sAsB_inv, k)
}

