# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CXX_cor_nearPSD <- function(G, tau = 1e-5, iter_outer = 200L, iter_inner = 20L, maxit = 200L, err_tol = 1e-6, precg_err_tol = 1e-2, newton_err_tol = 1e-4) {
    .Call(`_bigsimr_CXX_cor_nearPSD`, G, tau, iter_outer, iter_inner, maxit, err_tol, precg_err_tol, newton_err_tol)
}

.cor_convert_double <- function(X, CASE) {
    .Call(`_bigsimr_cor_convert_double`, X, CASE)
}

.cor_convert_matrix <- function(X, CASE) {
    .Call(`_bigsimr_cor_convert_matrix`, X, CASE)
}

hermite <- function(x, n) {
    .Call(`_bigsimr_hermite`, x, n)
}

